version: '3'
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: app
    entrypoint: "pipenv install"
    tty: false
    working_dir: /app
    volumes:
      - ./:/app
