name: Build
on: [push, pull_request]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up development Docker Buildx
        id: development_builder
        uses: docker/setup-buildx-action@v1
      -
        name: Build testing container
        uses: docker/build-push-action@v2
        with:
          push: false
          builder: ${{ steps.development_builder.outputs.name }}
          target: development
          load: true
          tags: movie-quote-twitter-bot-testing:latest
      - 
        name: Run tests
        uses: addnab/docker-run-action@v1
        with:
          image: movie-quote-twitter-bot-testing:latest
          shell: sh 
          run: sh /app/run_tests_ci ${{ github.sha }} ${{ secrets.CODECOV_TOKEN }}
      -
        name: Set up production Docker Buildx
        if: startsWith(github.ref, 'refs/tags')
        id: production_builder
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        if: startsWith(github.ref, 'refs/tags')
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push production container
        if: startsWith(github.ref, 'refs/tags')
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          builder: ${{ steps.production_builder.outputs.name }}
          target: production
          tags: namelivia/movie-quote-twitter-bot:latest
